export { prisma } from './client';
export {
  AIFeature,
  AIUsageStatus,
  ChecklistExecutionStatus,
  ChecklistItemStatus,
  DocumentStatus,
  DocumentType,
  FineSeverity,
  FineStatus,
  IncidentStatus,
  IncidentType,
  Prisma,
  PrismaClient,
  FuelType,
  MaintenanceType,
  NotificationType,
  PlanType,
  ServiceOrderStatus,
  TenantStatus,
  TireStatus,
  UserRole,
  VehicleCategory,
  VehicleStatus,
} from '@prisma/client';
