export { prisma } from './client';
export {
  AIFeature,
  AIUsageStatus,
  AIChatMessageRole,
  AIReportKind,
  AIReportStatus,
  AIAnomalyKind,
  AIAnomalySeverity,
  AIAnomalyStatus,
  ChecklistExecutionStatus,
  ChecklistItemStatus,
  DocumentStatus,
  DocumentType,
  FineSeverity,
  FineStatus,
  IncidentStatus,
  IncidentType,
  Prisma,
  PrismaClient,
  FuelType,
  MaintenanceType,
  NotificationType,
  PlanType,
  ResponsibilityTermStatus,
  ServiceOrderStatus,
  TenantStatus,
  TireStatus,
  UserRole,
  VehicleCategory,
  VehicleStatus,
} from '@prisma/client';

export type {
  AIChatSession,
  AIChatMessage,
  AIUsageLog,
  AITenantQuota,
  AIReport,
  AIAnomaly,
  DriverScore,
  ResponsibilityTerm,
  Tenant,
  User,
  Vehicle,
  Driver,
  FuelRecord,
  ServiceOrder,
  Document,
  Fine,
  Incident,
  MaintenancePlan,
  Tire,
} from '@prisma/client';
